package com.github.rougsig.filetemplateloader.constant

const val PROPS_FILE_NAME = "FILE_NAME"
const val PROPS_MODULE_NAME = "MODULE_NAME"
const val PROPS_PACKAGE_NAME = "PACKAGE_NAME"
const val PROPS_INITIAL_PACKAGE_NAME = "INITIAL_PACKAGE_NAME"
const val PROPS_MODULE_PACKAGE_NAME = "MODULE_PACKAGE_NAME"
const val PROPS_PACKAGE_NAME_TEMPLATE = "PACKAGE_NAME_TEMPLATE"

val REQUIRED_CONFIG_PROPS = listOf(
  PROPS_PACKAGE_NAME_TEMPLATE
)
