package com.github.rougsig.filetemplateloader.constant

const val PROP_TEMPLATE_EXTENSION = "TEMPLATE_EXTENSION"
const val PROP_TEMPLATE_NAME = "TEMPLATE_NAME"

const val PROP_FILE_NAME = "FILE_NAME"
const val PROP_MODULE_NAME = "MODULE_NAME"

const val PROP_PACKAGE_NAME = "PACKAGE_NAME"
const val PROP_INITIAL_PACKAGE_NAME = "INITIAL_PACKAGE_NAME"
const val PROP_MODULE_PACKAGE_NAME = "MODULE_PACKAGE_NAME"

const val PROP_PACKAGE_NAME_TEMPLATE = "PACKAGE_NAME_TEMPLATE"

val REQUIRED_CONFIG_PROPS = listOf(
  PROP_PACKAGE_NAME_TEMPLATE
)
